.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-REFACTOR" "1" "February 2014" "" "Git Extras"
.
.SH "NAME"
\fBgit\-refactor\fR \- Create refactor branch
.
.SH "SYNOPSIS"
\fBgit\-refactor\fR [finish] <name>
.
.SH "DESCRIPTION"
Manage refactor branch creation, deletion or merging back into integration branch\. By default the master branch is considered the integration branch\.
.
.P
If the bug branch name is not given, then a list of refactor branches will be displayed\.
.
.SH "OPTIONS"
<finish, fin, end, complete>
.
.P
Merge and delete the refactor branch\.
.
.P
<delete, del, remove, rm, clear>
.
.P
Delete the refactor branch from local and remote repositories\.
.
.P
<name>
.
.P
The name of the refactor branch\.
.
.SH "EXAMPLES"
.
.nf

$ git refactor mainlib_refactor
\.\.\.
$ git commit \-m "Some changes"
\.\.\.
$ git checkout master
$ git refactor finish mainlib_refactor
.
.fi
.
.SH "AUTHOR"
Written by Jesús Espino <\fIjespinog@gmail\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/visionmedia/git\-extras/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/visionmedia/git\-extras\fR>
